// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nkeuxlgnlrizgpqcgbol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5rZXV4bGdubHJpemdwcWNnYm9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc0NjU2ODMsImV4cCI6MjA4MzA0MTY4M30.oyhjyP6gXzxo6obrpUrMKiNuE3PgJIBusPE8X_DdvM4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);