// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chdldwqjuunnctnoyqzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoZGxkd3FqdXVubmN0bm95cXpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTQyMzEsImV4cCI6MjA2NTIzMDIzMX0.EyIeWaeexnZklFURiL3a69MyF7CZ-KR_I80XimsmmMc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);